version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]
  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]